### ISSUE TITLE
Taller Cards

### ISSUE THREAD

**Issue by Risath18** [CELC2023/website#17] opened 2022-04-18 17:14 UTC
![image](https://user-images.githubusercontent.com/66147598/163845702-a0ae0804-6653-4081-b88c-f52f760d27bc.png)

Increase the height of card to follow a 2:1 height to width ratio.

**Comment by rjb75** [comment] 2022-04-18 21:11
Duplicate of #13

**Closed** 2022-04-18 21:11 UTC
Labels: bug, help wanted, invalid
